//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestTests.ReservasWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaMatricula", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class ReservaMatricula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cd_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char fg_estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaReserva {
            get {
                return this.FechaReservaField;
            }
            set {
                if ((this.FechaReservaField.Equals(value) != true)) {
                    this.FechaReservaField = value;
                    this.RaisePropertyChanged("FechaReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cd_alumno {
            get {
                return this.cd_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.cd_alumnoField, value) != true)) {
                    this.cd_alumnoField = value;
                    this.RaisePropertyChanged("cd_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char fg_estado {
            get {
                return this.fg_estadoField;
            }
            set {
                if ((this.fg_estadoField.Equals(value) != true)) {
                    this.fg_estadoField = value;
                    this.RaisePropertyChanged("fg_estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservasWS.IReservasService")]
    public interface IReservasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/registarReserva", ReplyAction="http://tempuri.org/IReservasService/registarReservaResponse")]
        RestTests.ReservasWS.ReservaMatricula registarReserva(string cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/registarReserva", ReplyAction="http://tempuri.org/IReservasService/registarReservaResponse")]
        System.Threading.Tasks.Task<RestTests.ReservasWS.ReservaMatricula> registarReservaAsync(string cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/cancelarReserva", ReplyAction="http://tempuri.org/IReservasService/cancelarReservaResponse")]
        RestTests.ReservasWS.ReservaMatricula cancelarReserva(string cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservasService/cancelarReserva", ReplyAction="http://tempuri.org/IReservasService/cancelarReservaResponse")]
        System.Threading.Tasks.Task<RestTests.ReservasWS.ReservaMatricula> cancelarReservaAsync(string cd_alumno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservasServiceChannel : RestTests.ReservasWS.IReservasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservasServiceClient : System.ServiceModel.ClientBase<RestTests.ReservasWS.IReservasService>, RestTests.ReservasWS.IReservasService {
        
        public ReservasServiceClient() {
        }
        
        public ReservasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RestTests.ReservasWS.ReservaMatricula registarReserva(string cd_alumno) {
            return base.Channel.registarReserva(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<RestTests.ReservasWS.ReservaMatricula> registarReservaAsync(string cd_alumno) {
            return base.Channel.registarReservaAsync(cd_alumno);
        }
        
        public RestTests.ReservasWS.ReservaMatricula cancelarReserva(string cd_alumno) {
            return base.Channel.cancelarReserva(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<RestTests.ReservasWS.ReservaMatricula> cancelarReservaAsync(string cd_alumno) {
            return base.Channel.cancelarReservaAsync(cd_alumno);
        }
    }
}
