//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIDCode.WSLibrosPrestados {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int flag {
            get {
                return this.flagField;
            }
            set {
                if ((this.flagField.Equals(value) != true)) {
                    this.flagField = value;
                    this.RaisePropertyChanged("flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSLibrosPrestados.ILibrosPerstadosService")]
    public interface ILibrosPerstadosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosPerstadosService/ListarLibrosPrestados", ReplyAction="http://tempuri.org/ILibrosPerstadosService/ListarLibrosPrestadosResponse")]
        ProyectoIDCode.WSLibrosPrestados.Respuesta ListarLibrosPrestados(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosPerstadosService/ListarLibrosPrestados", ReplyAction="http://tempuri.org/ILibrosPerstadosService/ListarLibrosPrestadosResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSLibrosPrestados.Respuesta> ListarLibrosPrestadosAsync(string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibrosPerstadosServiceChannel : ProyectoIDCode.WSLibrosPrestados.ILibrosPerstadosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibrosPerstadosServiceClient : System.ServiceModel.ClientBase<ProyectoIDCode.WSLibrosPrestados.ILibrosPerstadosService>, ProyectoIDCode.WSLibrosPrestados.ILibrosPerstadosService {
        
        public LibrosPerstadosServiceClient() {
        }
        
        public LibrosPerstadosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibrosPerstadosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibrosPerstadosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibrosPerstadosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProyectoIDCode.WSLibrosPrestados.Respuesta ListarLibrosPrestados(string codigo) {
            return base.Channel.ListarLibrosPrestados(codigo);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSLibrosPrestados.Respuesta> ListarLibrosPrestadosAsync(string codigo) {
            return base.Channel.ListarLibrosPrestadosAsync(codigo);
        }
    }
}
