//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIDCode.WSMatricula {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Alumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cd_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cd_padreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cd_pagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_identificador_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cd_alumno {
            get {
                return this.cd_alumnoField;
            }
            set {
                if ((this.cd_alumnoField.Equals(value) != true)) {
                    this.cd_alumnoField = value;
                    this.RaisePropertyChanged("cd_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cd_padre {
            get {
                return this.cd_padreField;
            }
            set {
                if ((object.ReferenceEquals(this.cd_padreField, value) != true)) {
                    this.cd_padreField = value;
                    this.RaisePropertyChanged("cd_padre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cd_pago {
            get {
                return this.cd_pagoField;
            }
            set {
                if ((this.cd_pagoField.Equals(value) != true)) {
                    this.cd_pagoField = value;
                    this.RaisePropertyChanged("cd_pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_apellido {
            get {
                return this.ds_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_apellidoField, value) != true)) {
                    this.ds_apellidoField = value;
                    this.RaisePropertyChanged("ds_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_identificador_alumno {
            get {
                return this.ds_identificador_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_identificador_alumnoField, value) != true)) {
                    this.ds_identificador_alumnoField = value;
                    this.RaisePropertyChanged("ds_identificador_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_nombre {
            get {
                return this.ds_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_nombreField, value) != true)) {
                    this.ds_nombreField = value;
                    this.RaisePropertyChanged("ds_nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Padre", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Padre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cd_padreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cd_padre {
            get {
                return this.cd_padreField;
            }
            set {
                if ((this.cd_padreField.Equals(value) != true)) {
                    this.cd_padreField = value;
                    this.RaisePropertyChanged("cd_padre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_apellido {
            get {
                return this.ds_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_apellidoField, value) != true)) {
                    this.ds_apellidoField = value;
                    this.RaisePropertyChanged("ds_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_nombre {
            get {
                return this.ds_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_nombreField, value) != true)) {
                    this.ds_nombreField = value;
                    this.RaisePropertyChanged("ds_nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int flag {
            get {
                return this.flagField;
            }
            set {
                if ((this.flagField.Equals(value) != true)) {
                    this.flagField = value;
                    this.RaisePropertyChanged("flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaMatricula", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class ReservaMatricula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cd_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char fg_estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaReserva {
            get {
                return this.FechaReservaField;
            }
            set {
                if ((this.FechaReservaField.Equals(value) != true)) {
                    this.FechaReservaField = value;
                    this.RaisePropertyChanged("FechaReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cd_alumno {
            get {
                return this.cd_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.cd_alumnoField, value) != true)) {
                    this.cd_alumnoField = value;
                    this.RaisePropertyChanged("cd_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char fg_estado {
            get {
                return this.fg_estadoField;
            }
            set {
                if ((this.fg_estadoField.Equals(value) != true)) {
                    this.fg_estadoField = value;
                    this.RaisePropertyChanged("fg_estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nota", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Nota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cd_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cd_notaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double qt_notaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cd_alumno {
            get {
                return this.cd_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.cd_alumnoField, value) != true)) {
                    this.cd_alumnoField = value;
                    this.RaisePropertyChanged("cd_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cd_nota {
            get {
                return this.cd_notaField;
            }
            set {
                if ((this.cd_notaField.Equals(value) != true)) {
                    this.cd_notaField = value;
                    this.RaisePropertyChanged("cd_nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_curso {
            get {
                return this.ds_cursoField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_cursoField, value) != true)) {
                    this.ds_cursoField = value;
                    this.RaisePropertyChanged("ds_curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double qt_nota {
            get {
                return this.qt_notaField;
            }
            set {
                if ((this.qt_notaField.Equals(value) != true)) {
                    this.qt_notaField = value;
                    this.RaisePropertyChanged("qt_nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Observacion", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Observacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cd_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cd_observacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_comentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_profesorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cd_alumno {
            get {
                return this.cd_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.cd_alumnoField, value) != true)) {
                    this.cd_alumnoField = value;
                    this.RaisePropertyChanged("cd_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cd_observacion {
            get {
                return this.cd_observacionField;
            }
            set {
                if ((this.cd_observacionField.Equals(value) != true)) {
                    this.cd_observacionField = value;
                    this.RaisePropertyChanged("cd_observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_comentario {
            get {
                return this.ds_comentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_comentarioField, value) != true)) {
                    this.ds_comentarioField = value;
                    this.RaisePropertyChanged("ds_comentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_profesor {
            get {
                return this.ds_profesorField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_profesorField, value) != true)) {
                    this.ds_profesorField = value;
                    this.RaisePropertyChanged("ds_profesor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSMatricula.IReservaService")]
    public interface IReservaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ConsultarAlumno", ReplyAction="http://tempuri.org/IReservaService/ConsultarAlumnoResponse")]
        ProyectoIDCode.WSMatricula.Alumno ConsultarAlumno(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ConsultarAlumno", ReplyAction="http://tempuri.org/IReservaService/ConsultarAlumnoResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno> ConsultarAlumnoAsync(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ConsultarPadre", ReplyAction="http://tempuri.org/IReservaService/ConsultarPadreResponse")]
        ProyectoIDCode.WSMatricula.Padre ConsultarPadre(int cd_padre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ConsultarPadre", ReplyAction="http://tempuri.org/IReservaService/ConsultarPadreResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Padre> ConsultarPadreAsync(int cd_padre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/registarAlumno", ReplyAction="http://tempuri.org/IReservaService/registarAlumnoResponse")]
        ProyectoIDCode.WSMatricula.Alumno registarAlumno(int cd_padre, string ds_nombre, int cd_grado, string ds_apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/registarAlumno", ReplyAction="http://tempuri.org/IReservaService/registarAlumnoResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno> registarAlumnoAsync(int cd_padre, string ds_nombre, int cd_grado, string ds_apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarAlumno", ReplyAction="http://tempuri.org/IReservaService/ListarAlumnoResponse")]
        ProyectoIDCode.WSMatricula.Alumno[] ListarAlumno(string id_padre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarAlumno", ReplyAction="http://tempuri.org/IReservaService/ListarAlumnoResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno[]> ListarAlumnoAsync(string id_padre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarNotaAlumno", ReplyAction="http://tempuri.org/IReservaService/ListarNotaAlumnoResponse")]
        ProyectoIDCode.WSMatricula.Respuesta ListarNotaAlumno(string cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarNotaAlumno", ReplyAction="http://tempuri.org/IReservaService/ListarNotaAlumnoResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Respuesta> ListarNotaAlumnoAsync(string cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/registarReserva", ReplyAction="http://tempuri.org/IReservaService/registarReservaResponse")]
        ProyectoIDCode.WSMatricula.ReservaMatricula registarReserva(string cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/registarReserva", ReplyAction="http://tempuri.org/IReservaService/registarReservaResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.ReservaMatricula> registarReservaAsync(string cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/VerificarSituacionAcademica", ReplyAction="http://tempuri.org/IReservaService/VerificarSituacionAcademicaResponse")]
        ProyectoIDCode.WSMatricula.Nota[] VerificarSituacionAcademica(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/VerificarSituacionAcademica", ReplyAction="http://tempuri.org/IReservaService/VerificarSituacionAcademicaResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Nota[]> VerificarSituacionAcademicaAsync(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarLibrosPrestados", ReplyAction="http://tempuri.org/IReservaService/ListarLibrosPrestadosResponse")]
        ProyectoIDCode.WSMatricula.Respuesta ListarLibrosPrestados(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarLibrosPrestados", ReplyAction="http://tempuri.org/IReservaService/ListarLibrosPrestadosResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Respuesta> ListarLibrosPrestadosAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarPagos", ReplyAction="http://tempuri.org/IReservaService/ListarPagosResponse")]
        ProyectoIDCode.WSMatricula.Respuesta ListarPagos(string cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarPagos", ReplyAction="http://tempuri.org/IReservaService/ListarPagosResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Respuesta> ListarPagosAsync(string cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarObservacion", ReplyAction="http://tempuri.org/IReservaService/ListarObservacionResponse")]
        ProyectoIDCode.WSMatricula.Observacion[] ListarObservacion(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarObservacion", ReplyAction="http://tempuri.org/IReservaService/ListarObservacionResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Observacion[]> ListarObservacionAsync(int cd_alumno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaServiceChannel : ProyectoIDCode.WSMatricula.IReservaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaServiceClient : System.ServiceModel.ClientBase<ProyectoIDCode.WSMatricula.IReservaService>, ProyectoIDCode.WSMatricula.IReservaService {
        
        public ReservaServiceClient() {
        }
        
        public ReservaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProyectoIDCode.WSMatricula.Alumno ConsultarAlumno(int cd_alumno) {
            return base.Channel.ConsultarAlumno(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno> ConsultarAlumnoAsync(int cd_alumno) {
            return base.Channel.ConsultarAlumnoAsync(cd_alumno);
        }
        
        public ProyectoIDCode.WSMatricula.Padre ConsultarPadre(int cd_padre) {
            return base.Channel.ConsultarPadre(cd_padre);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Padre> ConsultarPadreAsync(int cd_padre) {
            return base.Channel.ConsultarPadreAsync(cd_padre);
        }
        
        public ProyectoIDCode.WSMatricula.Alumno registarAlumno(int cd_padre, string ds_nombre, int cd_grado, string ds_apellido) {
            return base.Channel.registarAlumno(cd_padre, ds_nombre, cd_grado, ds_apellido);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno> registarAlumnoAsync(int cd_padre, string ds_nombre, int cd_grado, string ds_apellido) {
            return base.Channel.registarAlumnoAsync(cd_padre, ds_nombre, cd_grado, ds_apellido);
        }
        
        public ProyectoIDCode.WSMatricula.Alumno[] ListarAlumno(string id_padre) {
            return base.Channel.ListarAlumno(id_padre);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno[]> ListarAlumnoAsync(string id_padre) {
            return base.Channel.ListarAlumnoAsync(id_padre);
        }
        
        public ProyectoIDCode.WSMatricula.Respuesta ListarNotaAlumno(string cd_alumno) {
            return base.Channel.ListarNotaAlumno(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Respuesta> ListarNotaAlumnoAsync(string cd_alumno) {
            return base.Channel.ListarNotaAlumnoAsync(cd_alumno);
        }
        
        public ProyectoIDCode.WSMatricula.ReservaMatricula registarReserva(string cd_alumno) {
            return base.Channel.registarReserva(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.ReservaMatricula> registarReservaAsync(string cd_alumno) {
            return base.Channel.registarReservaAsync(cd_alumno);
        }
        
        public ProyectoIDCode.WSMatricula.Nota[] VerificarSituacionAcademica(int cd_alumno) {
            return base.Channel.VerificarSituacionAcademica(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Nota[]> VerificarSituacionAcademicaAsync(int cd_alumno) {
            return base.Channel.VerificarSituacionAcademicaAsync(cd_alumno);
        }
        
        public ProyectoIDCode.WSMatricula.Respuesta ListarLibrosPrestados(string codigo) {
            return base.Channel.ListarLibrosPrestados(codigo);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Respuesta> ListarLibrosPrestadosAsync(string codigo) {
            return base.Channel.ListarLibrosPrestadosAsync(codigo);
        }
        
        public ProyectoIDCode.WSMatricula.Respuesta ListarPagos(string cd_alumno) {
            return base.Channel.ListarPagos(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Respuesta> ListarPagosAsync(string cd_alumno) {
            return base.Channel.ListarPagosAsync(cd_alumno);
        }
        
        public ProyectoIDCode.WSMatricula.Observacion[] ListarObservacion(int cd_alumno) {
            return base.Channel.ListarObservacion(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Observacion[]> ListarObservacionAsync(int cd_alumno) {
            return base.Channel.ListarObservacionAsync(cd_alumno);
        }
    }
}
