//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIDCode.WSPagos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int flag {
            get {
                return this.flagField;
            }
            set {
                if ((this.flagField.Equals(value) != true)) {
                    this.flagField = value;
                    this.RaisePropertyChanged("flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPagos.IPagosService")]
    public interface IPagosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/ListarPagos", ReplyAction="http://tempuri.org/IPagosService/ListarPagosResponse")]
        ProyectoIDCode.WSPagos.Respuesta ListarPagos(string cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagosService/ListarPagos", ReplyAction="http://tempuri.org/IPagosService/ListarPagosResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSPagos.Respuesta> ListarPagosAsync(string cd_alumno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagosServiceChannel : ProyectoIDCode.WSPagos.IPagosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagosServiceClient : System.ServiceModel.ClientBase<ProyectoIDCode.WSPagos.IPagosService>, ProyectoIDCode.WSPagos.IPagosService {
        
        public PagosServiceClient() {
        }
        
        public PagosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProyectoIDCode.WSPagos.Respuesta ListarPagos(string cd_alumno) {
            return base.Channel.ListarPagos(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSPagos.Respuesta> ListarPagosAsync(string cd_alumno) {
            return base.Channel.ListarPagosAsync(cd_alumno);
        }
    }
}
